# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: manuelgomezgomez <manuelgomezgomez@stud    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/06/09 11:28:37 by manuelgomez       #+#    #+#              #
#    Updated: 2023/07/03 11:04:36 by manuelgomez      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a

CC = g

RM = rm -f

CFLAGS = -Wall -Wextra -Werror

SRC	=	src/ft_printf.c \
		src/ft_printformat.c
		
OBJ = $(SRC:.c=.o)

all: $(NAME)
# replace, create, sort
$(NAME):    $(OBJ)
		ar rcs $(NAME) $(OBJ)
# Remove any object files generated by the build process
clean:
		$(RM) $(OBJ)
# The fclean target first runs the clean target to remove intermediate files,
# and then uses the $(RM) and $(NAME) variables to delete the final output files.	
fclean:    clean
		$(RM) $(NAME)

# Therefore, if you ran the re target in this Makefile, it would first remove all object files (using the fclean target),
# and then build the $(NAME) target to create the final executable file. 
# This would ensure that the project is built from a clean state, without any stale files or other artifacts from previous builds.
re:	fclean $(NAME)
